### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by BestOfAfrica** [TheBosoYolo/delay-packets#1]
config for it
example:
make it so that u can switch from hold to toggle
and make it so that you can hide or show the stuff in chat.
and make it so that it works in gui's
and make it so that it can get **timed.**

**Comment by AgentKosticka** [comment]
Sounds good. Working on mod menu intregration rn

**Comment by AgentKosticka** [comment]
Dear @BestOfAfrica, in the latest 1.1. versions the following things were implemented:
config
you can switch from hold to toggle
you can hide or show chat feedback
you can hide or show the fake player
it should in theory work in gui's, but for that i stronly recommend [UI Utils](https://github.com/Coderx-Gamer/ui-utils)

on a 1.20.x version and on being able to set a custom delay rather than hold all packets and release them at once is being worked on. Deep thanks for your suggestion
